name: Frontend CI
on: push
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - run: git lfs checkout
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - run: npm ci
    - run: npm run build:local
    - run: npm run lint
    - run: npm run typecheck
    - run: npm run test
